name: Java CI with Allure Report (deploy to GitHub Pages)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn clean test
        env:
          ENV: ${{ secrets.ENV }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        continue-on-error: true

      - name: Install Allure CLI (via tarball, faster than brew)
        run: |
          wget -q https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -xzf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
          allure --version

      - name: Generate Allure report
        if: always()
        run: |
          mkdir -p target/allure-results
          allure generate target/allure-results --clean -o allure-report-${{ env.ENV }}

      - name: Upload Allure report as GitHub Actions artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ env.ENV }}
          path: allure-report-${{ env.ENV }}

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report-${{ env.ENV }}
